# The URL the site will be built for
base_url = "innerfirexy.github.io"

title = "CLCS Research Blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true # Whether to automatically compile all Sass files in the sass directory

# theme = "anpu" # https://www.getzola.org/themes/anpu/
theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "light" # light, dark, auto, toggle
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "记录|posts", url = "/posts", weight = 1 },
    #{ name = "/projects", url = "/projects", weight = 2 },
    { name = "关于|about", url = "/about", weight = 1 },
]

socials = [
    { name = "github", url = "https://github.com/CLCS-SUSTech", icon = "github" },
]